# Generated by Django 2.2.17 on 2021-03-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
