# Generated by Django 2.2.17 on 2021-03-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagtube', '0002_auto_20210330_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hashtagtube.UserProfile'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtagtube.UserProfile'),
        ),
    ]
