# Generated by Django 2.2.17 on 2021-04-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagtube', '0012_auto_20210405_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
